### ISSUE TITLE
BPM is different than running aubio separate from it

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [adamjakab/BeetsPluginBpmAnalyser#10]
### Problem

I have noticed that using aubio to tag my files with the script below generates a different value for BPM than this plugin. I wonder why? Which one do you think is more accurate?

```
#!/bin/bash

export PATH=/Library/Frameworks/Python.framework/Versions/3.9/bin/:/usr/bin/:/bin/

for file in "$@"
do
    # Get the filename without extension
    filename=$(basename "$file")
    extension="${filename##*.}"
    filename="${filename%.*}"

    # Use aubio to find the BPM of the audio file
    bpm=$(aubio tempo "$file" | awk '{printf("%.0f\n", $1)}')

	# Write the BPM to the ID3 tag using eyeD3
    eyeD3 "$file" --bpm="$bpm"
done
```

**Comment by adamjakab** [comment]
Interesting! This plugin also uses aubio but I just recently discovered that as of December 2023 (https://github.com/aubio/aubio/issues/116) it doesn't work anymore.
Anyhow, how much difference do you see in the bpm values?

**Comment by 2V3EvG4LMJFdRe** [comment]
To be honest, I was just looking casually on this at the time and ended up not following through with a workflow that includes bpm data since I figured I personally don't listen to electronic music that much. Suppose it's meant for DJs, but my playlists aren't that advanced.

**Comment by adamjakab** [comment]
Got it. Thanks for letting me know. I will close this issue as it is not an issue anymore ;).

@2V3EvG4LMJFdRe - Btw, BPM is not only for electronic music. I listen to a lot of different genres. It is a good way to classify music by "speed". I use BPM in conjunction with this [BeetsPluginGoingRunning](https://github.com/adamjakab/BeetsPluginGoingRunning) plugin to generate me playlists based on a series of attributes including BPM. But I do understand that it might not be the case for you.

Last thought (for future readers): In relation to your original question, this library determines overall song BPM by scanning though the song, taking samples, determining BPM of the sample and then calculating an average for the entire song ([ref](https://github.com/adamjakab/BeetsPluginBpmAnalyser/blob/94a17f486bc7a5fbc51e07d8ea80ed99fdff9cf9/beetsplug/bpmanalyser/get_song_bpm.py#L42)). If a song has a steady rhythm this method produces a valid result. If a song often changes speed the average will be... an average.

**Comment by 2V3EvG4LMJFdRe** [comment]
It's always good to have more data available! That's encouraging that you can use it with more genres, I'll definitely look into it down the line. Thanks for updating the script.
